spring:
  application:
    name: employee
  data:
    mongodb:
      uri: mongodb://user23H:RdmSMRVlXfYxwtRo@mongodb/mongodb
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"